CREATE TABLE IF NOT EXISTS `GENERAL_DATA` (
  `kindofdata` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField1` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField2` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField3` varchar(100) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField4` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField5` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField6` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField7` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField8` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField9` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL,
  `DataField10` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `DataField11` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `DataField12` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `DataField13` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `DataField14` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `DataField15` varchar(256) CHARACTER SET latin1 COLLATE latin1_bin NOT NULL DEFAULT '',
  `DataField16` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField17` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField18` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField19` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField20` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField21` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField22` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField23` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField24` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField25` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField26` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField27` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField28` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField29` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField30` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField31` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField32` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField33` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField34` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField35` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField36` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField37` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField38` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField39` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField40` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField41` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField42` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField43` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField44` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField45` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField46` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField47` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField48` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField49` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField50` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField51` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField52` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField53` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField54` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField55` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField56` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField57` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField58` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField59` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField60` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField61` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField62` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField63` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField64` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField65` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField66` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField67` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField68` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField69` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField70` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField71` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField72` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField73` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField74` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField75` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField76` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField77` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField78` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField79` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField80` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField81` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField82` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField83` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField84` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField85` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField86` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField87` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField88` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField89` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField90` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField91` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField92` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField93` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField94` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField95` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField96` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField97` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField98` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField99` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  `DataField100` varchar(256) CHARACTER SET latin1 NOT NULL DEFAULT '',
  KEY `mf_general_purpose_table_idx1` (`kindofdata`,`DataField1`,`DataField2`,`DataField6`),
  KEY `mf_general_purpose_table_idx2` (`kindofdata`,`DataField2`,`DataField5`),
  KEY `_mf_general_purpose_table_idx3` (`kindofdata`,`DataField1`,`DataField3`),
  KEY `mf_general_purpose_table_idx4` (`kindofdata`,`DataField8`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_general_cs;

