CREATE TABLE ITEMCODES (
	ITEMCODE VARCHAR PRIMARY KEY,
	ITEMDESCRIPTION VARCHAR NOT NULL,
)


CREATE TABLE PRODUCTIONLINE (
	LINECODE VARCHAR PRIMARY KEY,
	LINEDESCRIPTION VARCHAR NOT NULL,
)


-- Create a sequence
CREATE SEQUENCE id_seq START 1


CREATE TABLE SITES (
	ID INTEGER PRIMARY KEY DEFAULT nextval('id_seq'),
	SITE VARCHAR NOT NULL,
	DESCRIPTION VARCHAR NOT NULL
)

